version: '2.4'


services:
  ml_api:
    hostname: ml_api
    restart: unless-stopped
    ports:
      - "3333:3333"
    runtime: nvidia
    build:
      context: ml_api
    environment:
        DEBUG: 'True'
        FLASK_APP: 'server.py'
        # ML_API_TOKEN:
        HAS_GPU: 'True'
    command: bash -c "gunicorn --bind 0.0.0.0:3333 --workers 6 wsgi"